#!/bin/bash
BIRed='\033[1;91m'        # Red
BIGreen='\033[1;92m'      # Green
BIYellow='\033[1;93m'     # Yellow
BIBlue='\033[1;94m'       # Blue
BIPurple='\033[1;95m'     # Purple
BICyan='\033[1;96m'       # Cyan
NORMAL="\033[0;39m"
clear
target="None"
my_head()
{
	echo -e ¤$BIPurple"--------------------------------------------------------------------------------------------------------------"
					 		echo -e " Automation tool for Unix Tasks!!\c"
							echo -e " \tTarget server : $target"
							echo -e "---------------------------------------------------------------------------------------------------------------"$NORMAL
}

while true
do
	my_head
	echo -e $BIRed"\n Please select your choice from below menu \n"
	echo -e " 1. Pre-validation \n"
	echo -e " 2. User Administration \n"
	echo -e " 3. Run AD Hoc Commands \n"
	echo -e " 10. Select target servers\n"
	echo -e " 0. Exit \n"$NORMAL
	read aux
	case $aux in

	0)
	break
	;;
	1)
	if [ $target = "None" ]; then
		echo -e "Select Target servers from option 10"
		read dummy
	else
	cat pre_validation.yml | sed "s/abcz/$target/g" > pre_validation_with_server.yml
	ansible-playbook pre_validation_with_server.yml -K -v
	sleep 2
fi
	;;
	2)
	if [ $target = "None" ]; then
		echo -e "Select Target servers from option 10"
		read dummy
	else
	while true
	do
		echo -e $BIPurple" 1. User Creation \n"
		echo -e " 2. User Removal \n"
		echo -e " 3. Password reset\n"
		echo -e " 0. Exit \n"$NORMAL
		read menu2
		case $menu2 in

			0)
			clear
			break
			;;
			1)
			cat user_creation.yml | sed "s/abcz/$target/g" > user_creation_with_server.yml
			#cat roles/add_sudoers/tasks/add_sudoers_template.yml | sed "s/abcz/$target/g" > roles/add_sudoers/tasks/main.yml
			python user_credentials.py
			;;
			2)
			cat user_remove.yml | sed "s/abcz/$target/g" > user_remove_with_server.yml
			python user_credentials_removal.py
			;;
			3)
			cat password_reset.yml | sed "s/abcz/$target/g" > password_reset_with_server.yml
			python password_credentials.py
			;;
			*)
			echo -e " Wrong choice ! \n"
			read dummy
			continue
			;;
		esac
	done
fi
	;;
	3)
	if [ $target = "None" ]; then
		echo -e "Select Target servers from option 10"
		read dummy
	else
	echo "Welcome to AD Hoc Commands"
	sleep 2
fi
	;;
	10)
	while true
	do
		clear
		my_head
		echo -e "1. Target Server \n"
		echo -e "0. Exit \n"
		echo -e " Enter your choice: \c"
		read cho
		case $cho in
			0)
			clear
			break
			;;
			1)
			echo -e "---------------------------------------------------------------------------------------------------"
			echo -e "Available Env : ALL -> for ALL servers in this environment"
			cat /etc/ansible/hosts | grep "\[" | sed "s/\[/ /g" | sed "s/\]/ /g" | sed "s/\ / /g"
			echo -e "---------------------------------------------------------------------------------------------------"
			echo -e "Enter your choice: \c"
			read target
			;;
			*)
			echo -e "Wrong choice ! \n"
			read dummy
			continue
			;;
		esac
	done
	;;
	*)
	echo -e "Wrong choice ! \n"
	read dummy
	continue
	;;
	esac
done
