---
- hosts: server1
  become: true
  become_user: root
  become_method: su
  vars:
    password: Osiatis31
    userid: userid_var
    username: thor
  tasks:

    - name: User exist
      shell: id {{ username }}
      register: user_exist
      ignore_errors: yes

    - debug: msg="User name {{ username }} is not existing on {{ ansible_hostname }}"
      when: user_exist.rc != 0

    - name: password reset
      user: name={{ username }} update_password=always password={{ password }}
      when: user_exist.rc == 0
      register: user_creation

    - debug: msg="Password has been reset for user {{ username }} on {{ ansible_hostname }}"
      when: user_creation.changed
